# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build & test @ push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '15'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --settings settings.xml deploy -DaltDeploymentRepository=snapshots::default::https://fortifiedid.jfrog.io/artifactory/default-fortifiedid-libs-snapshot-local/
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD_EXT }}
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME_EXT }}
